### ISSUE TITLE
How to calculate FVD for SEVIR-LR

### ISSUE THREAD

**Issue by jasong-ovo** [gaozhihan/PreDiff#11]
Hello, I have no idea about how to calculate FVD for sevir-lr. The input channel of I3D is 3, while sevir-lr has 1 channel. Could you show me how to calculate FVD for sevir?

**Comment by gaozhihan** [comment]
Thank you for your interest in our work and our question. We simply duplicate the channels from 1 to 3. We may want to refer to our [implementation](https://github.com/gaozhihan/PreDiff/blob/ff1f8005dc368ded30b5849a0815c76e0b891dc6/src/prediff/evaluation/fvd/torchmetrics_wrap.py#L232) for more details. As discussed in Sec. 3.1, we used FVD to compare models relative to each other, not for direct comparison to natural videos.
