### ISSUE TITLE
The loss become negative when training PreDiff

### ISSUE THREAD

**Issue by bugsuse** [gaozhihan/PreDiff#28]
I want to apply the PreDiff to my dataset for precipitation nowcasting, and I have already trained a Variational Autoencoder (VAE), and everything is normal. However, during the training of PreDiff, I encountered a situation where the loss became negative. In the PreDiff configuration file, apart from changing the data path and size of the sample (input length, target length, height and wight), the rest of the parameters remained unchanged. Upon checking the logs, I found that the loss of logvar was negative. Do you have any suggestions? Any help would be appreciated!

![WechatIMG19749](https://github.com/gaozhihan/PreDiff/assets/16102453/930362f2-042c-4744-b0f6-a5e372d60d80)
![WechatIMG19747](https://github.com/gaozhihan/PreDiff/assets/16102453/e9865e72-18d1-48b5-b7f1-6d9d1dc816c7)
![WechatIMG19779](https://github.com/gaozhihan/PreDiff/assets/16102453/a268cc48-7618-4e93-b561-2c59bfcd519c)
![WechatIMG19780](https://github.com/gaozhihan/PreDiff/assets/16102453/d2a708ab-0778-4c03-86ad-21cd94769abf)
![WechatIMG19781](https://github.com/gaozhihan/PreDiff/assets/16102453/0a917a6c-558d-44e0-a07d-6cf8b63980b5)

**Comment by gaozhihan** [comment]
Thank you for raising this question. The `logvar` parameter is directly adopted from the original [Stable Diffusion implementation](https://github.com/CompVis/stable-diffusion/blob/21f890f9da3cfbeaba8e2ac3c425ee9e998d5229/ldm/models/diffusion/ddpm.py#L1035C13-L1035C66) without modification. This phenomenon is also observed there:

https://github.com/CompVis/stable-diffusion/issues/380

According to our trials, it is common for `loss` and `logvar` to become negative during training, without any constraints placed on limiting their range.
